#!/usr/bin/env python3
import json
import argparse
import os
import sys

def main():
    parser = argparse.ArgumentParser(description="Generate rotated charset assembly from JSON")
    parser.add_argument("-i", "--input", required=True, help="Path to rotated.json")
    parser.add_argument("-g", "--global-out", required=True, help="Path to output global .asm file")
    parser.add_argument("-p", "--proc-out", required=True, help="Path to output proc .asm file")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' does not exist.", file=sys.stderr)
        return 1

    try:
        with open(args.input, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading/parsing input JSON: {e}", file=sys.stderr)
        return 1

    characters = data.get("characters", [])
    num_chars = len(characters)

    # Ensure output directories exist
    for out_path in [args.global_out, args.proc_out]:
        out_dir = os.path.dirname(out_path)
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)

    try:
        with open(args.global_out, "w", encoding="utf-8") as f:
            f.write("; Generated by gen_rotated_charset.py. Do not edit.\n\n")
            f.write(f"ANIM_CHAR_COUNT = {num_chars}\n\n")
            
            bit_masks = [str(1 << idx) for idx in range(num_chars)]
            f.write("anim_char_bit_masks\n")
            if num_chars > 0:
                f.write(f"\tdta {', '.join(bit_masks)}\n\n")
            else:
                f.write("\n")

        with open(args.proc_out, "w", encoding="utf-8") as f:
            f.write("; Generated by gen_rotated_charset.py. Do not edit.\n\n")
            
            char_ids = [str(char_info["index"]) for char_info in characters]
            durations = [str(char_info["duration"]) for char_info in characters]
            
            f.write("anim_char_ids\n")
            if num_chars > 0:
                f.write(f"\tdta {', '.join(char_ids)}\n\n")
            else:
                f.write("\n")

            f.write("anim_char_speeds\n")
            if num_chars > 0:
                f.write(f"\tdta {', '.join(durations)}\n\n")
            else:
                f.write("\n")

            f.write("anim_char_counters\n")
            if num_chars > 0:
                f.write(f"\tdta {', '.join(durations)}\n\n")
            else:
                f.write("\n")

    except Exception as e:
        print(f"Error writing output files: {e}", file=sys.stderr)
        return 1

    print("Successfully generated rotated charset assembly files.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
