#!/usr/bin/env python3
import json
import argparse
import os
import sys

def main():
    parser = argparse.ArgumentParser(description="Generate animated charset assembly from JSON")
    parser.add_argument("-i", "--input", required=True, help="Path to animated.json")
    parser.add_argument("-o", "--output", required=True, help="Path to output .asm file")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' does not exist.", file=sys.stderr)
        return 1

    try:
        with open(args.input, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading/parsing input JSON: {e}", file=sys.stderr)
        return 1

    characters = data.get("characters", [])
    num_chars = len(characters)

    # Ensure output directory exists
    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    try:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write("; Generated by gen_animated_charset.py. Do not edit.\n\n")
            f.write(f"NUM_ANIM_CHARS = {num_chars}\n\n")

            if num_chars == 0:
                # If no animated characters, generate empty labels
                f.write("animated_char_dest_lo\n")
                f.write("animated_char_dest_hi\n")
                f.write("animated_char_max_frames\n")
                f.write("animated_char_durations_lo\n")
                f.write("animated_char_durations_hi\n")
                f.write("animated_char_data_lo\n")
                f.write("animated_char_data_hi\n")
                f.write("animated_char_cur_frame\n")
                f.write("animated_char_timers\n")
                f.write("animated_char_ids\n")
                f.write("animated_char_bit_masks\n")
                return 0

            # Write dest lo/hi tables
            dest_lo = []
            dest_hi = []
            max_frames = []
            durations_lo = []
            durations_hi = []
            data_lo = []
            data_hi = []
            char_ids = []
            bit_masks = []

            for idx, char_info in enumerate(characters):
                char_idx = char_info["index"]
                dest_addr = 0x6400 + char_idx * 8
                dest_lo.append(f"<{dest_addr}")
                dest_hi.append(f">{dest_addr}")
                
                frames = char_info["frames"]
                num_frames = len(frames)
                if num_frames > 32:
                    print(f"Warning: Character at index {char_idx} has {num_frames} frames (max supported is 32).", file=sys.stderr)
                
                max_frames.append(str(num_frames))
                
                durations_lo.append(f"<char{idx}_durations")
                durations_hi.append(f">char{idx}_durations")
                
                data_lo.append(f"<char{idx}_data")
                data_hi.append(f">char{idx}_data")
                
                char_ids.append(str(char_idx))
                bit_masks.append(str(1 << (2 + idx)))

            f.write("animated_char_dest_lo\n")
            f.write(f"\tdta {', '.join(dest_lo)}\n\n")

            f.write("animated_char_dest_hi\n")
            f.write(f"\tdta {', '.join(dest_hi)}\n\n")

            f.write("animated_char_max_frames\n")
            f.write(f"\tdta {', '.join(max_frames)}\n\n")

            f.write("animated_char_durations_lo\n")
            f.write(f"\tdta {', '.join(durations_lo)}\n\n")

            f.write("animated_char_durations_hi\n")
            f.write(f"\tdta {', '.join(durations_hi)}\n\n")

            f.write("animated_char_data_lo\n")
            f.write(f"\tdta {', '.join(data_lo)}\n\n")

            f.write("animated_char_data_hi\n")
            f.write(f"\tdta {', '.join(data_hi)}\n\n")

            # Write current frames (initialized to 255 for first-frame wrap-around to 0)
            cur_frames_init = [ "255" for _ in range(num_chars) ]
            f.write("animated_char_cur_frame\n")
            f.write(f"\tdta {', '.join(cur_frames_init)}\n\n")

            # Write timers (initialized to 1 to trigger immediate decrement -> update on first frame)
            timers_init = [ "1" for _ in range(num_chars) ]
            f.write("animated_char_timers\n")
            f.write(f"\tdta {', '.join(timers_init)}\n\n")

            # Write animated character IDs and bitmasks
            f.write("animated_char_ids\n")
            f.write(f"\tdta {', '.join(char_ids)}\n\n")

            f.write("animated_char_bit_masks\n")
            f.write(f"\tdta {', '.join(bit_masks)}\n\n")

            # Write duration and frame data arrays for each character
            for idx, char_info in enumerate(characters):
                f.write(f"; Character {char_info['index']}\n")
                
                # durations
                durations = [str(frame["duration"]) for frame in char_info["frames"]]
                f.write(f"char{idx}_durations\n")
                f.write(f"\tdta {', '.join(durations)}\n")
                
                # data frames
                f.write(f"char{idx}_data\n")
                for frame in char_info["frames"]:
                    hex_bytes = frame["data"].split()
                    decimal_bytes = [str(int(b, 16)) for b in hex_bytes]
                    f.write(f"\tdta {', '.join(decimal_bytes)}\n")
                f.write("\n")

    except Exception as e:
        print(f"Error writing output file: {e}", file=sys.stderr)
        return 1

    print(f"Successfully generated animated charset assembly to '{args.output}'")
    return 0

if __name__ == "__main__":
    sys.exit(main())
